<?php

namespace Isics\GlossaryBundle\Entity;

use Isics\Glossary\Model\Form\Search;

use Doctrine\ORM\EntityRepository;

/**
 * TermRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TermRepository extends EntityRepository
{
    /**
     * Returns all terms ordered alphabetically.
     *
     * @return collection of terms
     */
    public function findAllOrderedByTerm()
    {
        return $this->getEntityManager()
            ->createQuery('SELECT t FROM IsicsGlossaryBundle:Term t ORDER BY t.term')
            ->getResult();
    }
    
    /**
     * Returns terms found ordered alphabetically.
     *
     * @param String $keywords
     * @return array
     */
    public function findByKeywordsAndOrderedByTerm($keywords)
    {
        return $this->getEntityManager()
            ->createQuery('SELECT t
                FROM IsicsGlossaryBundle:Term t 
                WHERE t.term LIKE :keywords
                OR t.definition LIKE :keywords
                ORDER BY t.term
            ')
            ->setParameter('keywords', '%'.$keywords.'%')
            ->getResult();
    }
}