<?php

namespace Isics\GlossaryBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * TermRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TermRepository extends EntityRepository
{
    /**
     * Returns all terms ordered alphabetically.
     *
     * @return collection of terms
     */
    public function findAllOrderedByTerm()
    {
        return $this->getEntityManager()
            ->createQuery('SELECT t FROM IsicsGlossaryBundle:Term t ORDER BY t.term')
            ->getResult();
    }
}